# Generated by Django 2.1.7 on 2019-02-24 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0001_initial'),
    ]

    operations = [migrations.RunSQL("""
                    CREATE OR REPLACE VIEW board_results as with last_vote as
                    (select distinct on (issue_id,voter_ref) * from voter_vote)
                    , sum_votes as
                    (select issue_id, sum(grade) as total_votes
                        from last_vote group by issue_id )
                    select s.issue_id, i.description, s.total_votes
                        from sum_votes as s
                        inner join voter_issue as i
                            on i.id = s.issue_id
                        order by issue_id desc;
                    """,
        "DROP VIEW board_results;")
    ]
